//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsisTravelCore.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IsisTravelCore.Resources.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUIENES SOMOS.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casa - Sobre nosotros.
        /// </summary>
        public static string AboutUsTitle {
            get {
                return ResourceManager.GetString("AboutUsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocupaciones.
        /// </summary>
        public static string Activity {
            get {
                return ResourceManager.GetString("Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to panel de administración.
        /// </summary>
        public static string AdminPanel {
            get {
                return ResourceManager.GetString("AdminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adulto.
        /// </summary>
        public static string Adult {
            get {
                return ResourceManager.GetString("Adult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Estás listo para reservar un tour?.
        /// </summary>
        public static string AreYouReadyToBookATour {
            get {
                return ResourceManager.GetString("AreYouReadyToBookATour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bebé.
        /// </summary>
        public static string Baby {
            get {
                return ResourceManager.GetString("Baby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservar ahora.
        /// </summary>
        public static string BookNow {
            get {
                return ResourceManager.GetString("BookNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las categorías.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorías y hoteles.
        /// </summary>
        public static string CategoriesAndHotels {
            get {
                return ResourceManager.GetString("CategoriesAndHotels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulsa sobre la categoría para ver los hoteles.
        /// </summary>
        public static string CategoriesAndHotelsTitle {
            get {
                return ResourceManager.GetString("CategoriesAndHotelsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elegir la categoría.
        /// </summary>
        public static string ChooseCategory {
            get {
                return ResourceManager.GetString("ChooseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elegir la City.
        /// </summary>
        public static string ChooseCity {
            get {
                return ResourceManager.GetString("ChooseCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necesitas un Viaje a Medida y tu Agencia de Viajes no te lo ofrece?.
        /// </summary>
        public static string ContactInformation {
            get {
                return ResourceManager.GetString("ContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viajes a Medida.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destinos.
        /// </summary>
        public static string Destinations {
            get {
                return ResourceManager.GetString("Destinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descúbrelo ahora para cosas increíbles desde allí..
        /// </summary>
        public static string DiscoverItNowForIncredibleThingsFromThere {
            get {
                return ResourceManager.GetString("DiscoverItNowForIncredibleThingsFromThere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descubrir ahora.
        /// </summary>
        public static string DiscoverNow {
            get {
                return ResourceManager.GetString("DiscoverNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doble.
        /// </summary>
        public static string Double {
            get {
                return ResourceManager.GetString("Double", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niño.
        /// </summary>
        public static string ExtraRoom {
            get {
                return ResourceManager.GetString("ExtraRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preguntas frecuentes.
        /// </summary>
        public static string FAQs {
            get {
                return ResourceManager.GetString("FAQs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ofertas destacadas.
        /// </summary>
        public static string FeaturedTours {
            get {
                return ResourceManager.GetString("FeaturedTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siga con nosotros.
        /// </summary>
        public static string FollowUsOn {
            get {
                return ResourceManager.GetString("FollowUsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consigue una cotización.
        /// </summary>
        public static string GetAQuote {
            get {
                return ResourceManager.GetString("GetAQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garantía.
        /// </summary>
        public static string Guarantee {
            get {
                return ResourceManager.GetString("Guarantee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historia.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string HomeNav {
            get {
                return ResourceManager.GetString("HomeNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoteles.
        /// </summary>
        public static string Hotels {
            get {
                return ResourceManager.GetString("Hotels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itinerario de viaje.
        /// </summary>
        public static string Intinerary {
            get {
                return ResourceManager.GetString("Intinerary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to palabras clave.
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sesión.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar sesión.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese su mensaje.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La mayoría de las vistas.
        /// </summary>
        public static string MostedViews {
            get {
                return ResourceManager.GetString("MostedViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi cuenta.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi presupuesto.
        /// </summary>
        public static string myBudget {
            get {
                return ResourceManager.GetString("myBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoja informativa.
        /// </summary>
        public static string Newsletter {
            get {
                return ResourceManager.GetString("Newsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Nota: 1 habitación incluye 2 -3 clientes, excluyendo bebés menores de 12 años.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ofertas.
        /// </summary>
        public static string Offers {
            get {
                return ResourceManager.GetString("Offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En ventas.
        /// </summary>
        public static string OnSales {
            get {
                return ResourceManager.GetString("OnSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ofertas populares.
        /// </summary>
        public static string PopularTours {
            get {
                return ResourceManager.GetString("PopularTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recomendar.
        /// </summary>
        public static string Recommend {
            get {
                return ResourceManager.GetString("Recommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reembolso.
        /// </summary>
        public static string Refund {
            get {
                return ResourceManager.GetString("Refund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos de la habitación.
        /// </summary>
        public static string RoomType {
            get {
                return ResourceManager.GetString("RoomType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultado de búsqueda.
        /// </summary>
        public static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ofertas - Resultado de búsqueda.
        /// </summary>
        public static string SearchTitle {
            get {
                return ResourceManager.GetString("SearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar mensaje.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicios.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar Hoteles.
        /// </summary>
        public static string ShowHotels {
            get {
                return ResourceManager.GetString("ShowHotels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regístrese para suscribirse a nuestras últimas noticias y promociones más calientes. ¡Nunca enviamos spam!.
        /// </summary>
        public static string SignupToSubscribe {
            get {
                return ResourceManager.GetString("SignupToSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo.
        /// </summary>
        public static string Single {
            get {
                return ResourceManager.GetString("Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diapositivas.
        /// </summary>
        public static string Slideshow {
            get {
                return ResourceManager.GetString("Slideshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total parcial.
        /// </summary>
        public static string SubTotal {
            get {
                return ResourceManager.GetString("SubTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apoyo.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Términos y Condiciones.
        /// </summary>
        public static string TermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFERTAS DESTACADAS.
        /// </summary>
        public static string TopOffers {
            get {
                return ResourceManager.GetString("TopOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles de la oferta.
        /// </summary>
        public static string TourDetails {
            get {
                return ResourceManager.GetString("TourDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guías turísticos.
        /// </summary>
        public static string TourGuides {
            get {
                return ResourceManager.GetString("TourGuides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excursiones.
        /// </summary>
        public static string Tours {
            get {
                return ResourceManager.GetString("Tours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trible.
        /// </summary>
        public static string Trible {
            get {
                return ResourceManager.GetString("Trible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El viaje incluye.
        /// </summary>
        public static string TripInclude {
            get {
                return ResourceManager.GetString("TripInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver todas las ofertas.
        /// </summary>
        public static string ViewAllTours {
            get {
                return ResourceManager.GetString("ViewAllTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Detalle.
        /// </summary>
        public static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qué hay de nuevo.
        /// </summary>
        public static string WhatIsNew {
            get {
                return ResourceManager.GetString("WhatIsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu correo electrónico.
        /// </summary>
        public static string YourMail {
            get {
                return ResourceManager.GetString("YourMail", resourceCulture);
            }
        }
    }
}
